pub mod clamor_of_harpies;
pub use clamor_of_harpies::*;
pub mod flamecaller;
pub use flamecaller::*;
pub mod arid_desert;
pub use arid_desert::*;
pub mod askelon_phoenix;
pub use askelon_phoenix::*;
pub mod heat_ray;
pub use heat_ray::*;
pub mod pit_vipers;
pub use pit_vipers::*;
pub mod raal_dromedary;
pub use raal_dromedary::*;
pub mod lava_salamander;
pub use lava_salamander::*;
pub mod sacred_scarabs;
pub use sacred_scarabs::*;
pub mod wayfaring_pilgrim;
pub use wayfaring_pilgrim::*;
pub mod petrosian_cavalry;
pub use petrosian_cavalry::*;
pub mod sand_worm;
pub use sand_worm::*;
pub mod infernal_legion;
pub use infernal_legion::*;
pub mod mad_dash;
pub use mad_dash::*;
pub mod cornerstone;
pub use cornerstone::*;
pub mod red_desert;
pub use red_desert::*;
pub mod remote_desert;
pub use remote_desert::*;
pub mod shifting_sands;
pub use shifting_sands::*;
pub mod vesuvius;
pub use vesuvius::*;
pub mod colicky_dragonettes;
pub use colicky_dragonettes::*;
pub mod battlemage;
pub use battlemage::*;
pub mod sparkmage;
pub use sparkmage::*;
pub mod minor_explosion;
pub use minor_explosion::*;
pub mod major_explosion;
pub use major_explosion::*;
pub mod firebolts;
pub use firebolts::*;
pub mod incinerate;
pub use incinerate::*;
pub mod cone_of_flame;
pub use cone_of_flame::*;
pub mod rimland_nomads;
pub use rimland_nomads::*;
pub mod ogre_goons;
pub use ogre_goons::*;
pub mod quarrelsome_kobolds;
pub use quarrelsome_kobolds::*;
pub mod hillock_basilisk;
pub use hillock_basilisk::*;
pub mod escyllion_cyclops;
pub use escyllion_cyclops::*;
pub mod wildfire;
pub use wildfire::*;
pub mod fireball;
pub use fireball::*;
pub mod blaze;
pub use blaze::*;
pub mod sling_pixies;
pub use sling_pixies::*;
pub mod snow_leopard;
pub use snow_leopard::*;
pub mod cloud_spirit;
pub use cloud_spirit::*;
pub mod dead_of_night_demon;
pub use dead_of_night_demon::*;
pub mod spectral_stalker;
pub use spectral_stalker::*;
pub mod apprentice_wizard;
pub use apprentice_wizard::*;
pub mod headless_haunt;
pub use headless_haunt::*;
pub mod kite_archer;
pub use kite_archer::*;
pub mod midnight_rogue;
pub use midnight_rogue::*;
pub mod plumed_pegasus;
pub use plumed_pegasus::*;
pub mod spire_lich;
pub use spire_lich::*;
pub mod gyre_hippogriffs;
pub use gyre_hippogriffs::*;
pub mod skirmishers_of_mu;
pub use skirmishers_of_mu::*;
pub mod roaming_monster;
pub use roaming_monster::*;
pub mod grandmaster_wizard;
pub use grandmaster_wizard::*;
pub mod nimbus_jinn;
pub use nimbus_jinn::*;
pub mod highland_clansmen;
pub use highland_clansmen::*;
pub mod blink;
pub use blink::*;
pub mod chain_lightning;
pub use chain_lightning::*;
pub mod lightning_bolt;
pub use lightning_bolt::*;
pub mod teleport;
pub use teleport::*;
pub mod raise_dead;
pub use raise_dead::*;
pub mod cloud_city;
pub use cloud_city::*;
pub mod dark_tower;
pub use dark_tower::*;
pub mod gothic_tower;
pub use gothic_tower::*;
pub mod lone_tower;
pub use lone_tower::*;
pub mod mountain_pass;
pub use mountain_pass::*;
pub mod observatory;
pub use observatory::*;
pub mod planar_gate;
pub use planar_gate::*;
pub mod updraft_ridge;
pub use updraft_ridge::*;
pub mod lucky_charm;
pub use lucky_charm::*;
pub mod thunderstorm;
pub use thunderstorm::*;
pub mod geomancer;
pub use geomancer::*;
pub mod wild_boars;
pub use wild_boars::*;
pub mod land_surveyor;
pub use land_surveyor::*;
pub mod scent_hounds;
pub use scent_hounds::*;
pub mod autumn_unicorn;
pub use autumn_unicorn::*;
pub mod belmotte_longbowmen;
pub use belmotte_longbowmen::*;
pub mod cave_trolls;
pub use cave_trolls::*;
pub mod slumbering_giantess;
pub use slumbering_giantess::*;
pub mod dalcean_phalanx;
pub use dalcean_phalanx::*;

use crate::{card::Card, game::PlayerId};

pub fn from_beta_name(name: &str, player_id: PlayerId) -> Option<Box<dyn Card>> {
    match name {
        Flamecaller::NAME => Some(Box::new(Flamecaller::new(player_id))),
        ClamorOfHarpies::NAME => Some(Box::new(ClamorOfHarpies::new(player_id))),
        Battlemage::NAME => Some(Box::new(Battlemage::new(player_id))),
        AridDesert::NAME => Some(Box::new(AridDesert::new(player_id))),
        Sparkmage::NAME => Some(Box::new(Sparkmage::new(player_id))),
        AskelonPhoenix::NAME => Some(Box::new(AskelonPhoenix::new(player_id))),
        HeatRay::NAME => Some(Box::new(HeatRay::new(player_id))),
        PitVipers::NAME => Some(Box::new(PitVipers::new(player_id))),
        RaalDromedary::NAME => Some(Box::new(RaalDromedary::new(player_id))),
        LavaSalamander::NAME => Some(Box::new(LavaSalamander::new(player_id))),
        SacredScarabs::NAME => Some(Box::new(SacredScarabs::new(player_id))),
        WayfaringPilgrim::NAME => Some(Box::new(WayfaringPilgrim::new(player_id))),
        PetrosianCavalry::NAME => Some(Box::new(PetrosianCavalry::new(player_id))),
        SandWorm::NAME => Some(Box::new(SandWorm::new(player_id))),
        InfernalLegion::NAME => Some(Box::new(InfernalLegion::new(player_id))),
        MadDash::NAME => Some(Box::new(MadDash::new(player_id))),
        Cornerstone::NAME => Some(Box::new(Cornerstone::new(player_id))),
        RedDesert::NAME => Some(Box::new(RedDesert::new(player_id))),
        RemoteDesert::NAME => Some(Box::new(RemoteDesert::new(player_id))),
        ShiftingSands::NAME => Some(Box::new(ShiftingSands::new(player_id))),
        Vesuvius::NAME => Some(Box::new(Vesuvius::new(player_id))),
        ColickyDragonettes::NAME => Some(Box::new(ColickyDragonettes::new(player_id))),
        MinorExplosion::NAME => Some(Box::new(MinorExplosion::new(player_id))),
        MajorExplosion::NAME => Some(Box::new(MajorExplosion::new(player_id))),
        Firebolts::NAME => Some(Box::new(Firebolts::new(player_id))),
        Incinerate::NAME => Some(Box::new(Incinerate::new(player_id))),
        ConeOfFlame::NAME => Some(Box::new(ConeOfFlame::new(player_id))),
        RimlandNomads::NAME => Some(Box::new(RimlandNomads::new(player_id))),
        OgreGoons::NAME => Some(Box::new(OgreGoons::new(player_id))),
        QuarrelsomeKobolds::NAME => Some(Box::new(QuarrelsomeKobolds::new(player_id))),
        HillockBasilisk::NAME => Some(Box::new(HillockBasilisk::new(player_id))),
        EscyllionCyclops::NAME => Some(Box::new(EscyllionCyclops::new(player_id))),
        Wildfire::NAME => Some(Box::new(Wildfire::new(player_id))),
        Fireball::NAME => Some(Box::new(Fireball::new(player_id))),
        Blaze::NAME => Some(Box::new(Blaze::new(player_id))),
        SlingPixies::NAME => Some(Box::new(SlingPixies::new(player_id))),
        SnowLeopard::NAME => Some(Box::new(SnowLeopard::new(player_id))),
        CloudSpirit::NAME => Some(Box::new(CloudSpirit::new(player_id))),
        DeadOfNightDemon::NAME => Some(Box::new(DeadOfNightDemon::new(player_id))),
        SpectralStalker::NAME => Some(Box::new(SpectralStalker::new(player_id))),
        ApprenticeWizard::NAME => Some(Box::new(ApprenticeWizard::new(player_id))),
        HeadlessHaunt::NAME => Some(Box::new(HeadlessHaunt::new(player_id))),
        KiteArcher::NAME => Some(Box::new(KiteArcher::new(player_id))),
        MidnightRogue::NAME => Some(Box::new(MidnightRogue::new(player_id))),
        PlumedPegasus::NAME => Some(Box::new(PlumedPegasus::new(player_id))),
        SpireLich::NAME => Some(Box::new(SpireLich::new(player_id))),
        GyreHippogriffs::NAME => Some(Box::new(GyreHippogriffs::new(player_id))),
        SkirmishersOfMu::NAME => Some(Box::new(SkirmishersOfMu::new(player_id))),
        RoamingMonster::NAME => Some(Box::new(RoamingMonster::new(player_id))),
        GrandmasterWizard::NAME => Some(Box::new(GrandmasterWizard::new(player_id))),
        NimbusJinn::NAME => Some(Box::new(NimbusJinn::new(player_id))),
        HighlandClansmen::NAME => Some(Box::new(HighlandClansmen::new(player_id))),
        Blink::NAME => Some(Box::new(Blink::new(player_id))),
        ChainLightning::NAME => Some(Box::new(ChainLightning::new(player_id))),
        LightningBolt::NAME => Some(Box::new(LightningBolt::new(player_id))),
        Teleport::NAME => Some(Box::new(Teleport::new(player_id))),
        RaiseDead::NAME => Some(Box::new(RaiseDead::new(player_id))),
        CloudCity::NAME => Some(Box::new(CloudCity::new(player_id))),
        DarkTower::NAME => Some(Box::new(DarkTower::new(player_id))),
        GothicTower::NAME => Some(Box::new(GothicTower::new(player_id))),
        LoneTower::NAME => Some(Box::new(LoneTower::new(player_id))),
        MountainPass::NAME => Some(Box::new(MountainPass::new(player_id))),
        Observatory::NAME => Some(Box::new(Observatory::new(player_id))),
        PlanarGate::NAME => Some(Box::new(PlanarGate::new(player_id))),
        UpdraftRidge::NAME => Some(Box::new(UpdraftRidge::new(player_id))),
        LuckyCharm::NAME => Some(Box::new(LuckyCharm::new(player_id))),
        Thunderstorm::NAME => Some(Box::new(Thunderstorm::new(player_id))),
        Geomancer::NAME => Some(Box::new(Geomancer::new(player_id))),
        WildBoars::NAME => Some(Box::new(WildBoars::new(player_id))),
        LandSurveyor::NAME => Some(Box::new(LandSurveyor::new(player_id))),
        ScentHounds::NAME => Some(Box::new(ScentHounds::new(player_id))),
        AutumnUnicorn::NAME => Some(Box::new(AutumnUnicorn::new(player_id))),
        BelmotteLongbowmen::NAME => Some(Box::new(BelmotteLongbowmen::new(player_id))),
        CaveTrolls::NAME => Some(Box::new(CaveTrolls::new(player_id))),
        SlumberingGiantess::NAME => Some(Box::new(SlumberingGiantess::new(player_id))),
        DalceanPhalanx::NAME => Some(Box::new(DalceanPhalanx::new(player_id))),
        _ => None,
    }
}
